---
title: "Plotting HOBO outputs"
output: html_document
date: "2024-01-08"
---

```{r}
library(tidyverse)
library(data.table)
library(lubridate)
```

Load data
```{r}
# Example data
# from .hobo file that was exported to .csv in the HOBOware program
data <- fread("10596690_Birds_Mammals_Range.csv", skip=1, header=T)
colnames(data)  <- c("n","timestamp", "temp", "rh")

# change date/time to POSIXct class
data$time <- as.POSIXct(data$timestamp, format = "%m/%d/%y  %I:%M:%S %p")

# get just a date class for future filtering
data$date <- as.Date(data$time, format = "%m/%d/%Y")


min(data$date) 
max(data$date)
```


Plot
1) Temperature

* Add temp min 65 max 75 lines (hline) - done
* add function that highlights time periods where the value exceeds that threshold (rect)

```{r}
# Temperature
ggplot(data, aes(x=date, y=temp)) +
  geom_line() +
  geom_smooth(col="red") +
  geom_hline(aes(yintercept = 62), color="red", linetype="dashed") +
  geom_hline(aes(yintercept = 70), color="red", linetype="dashed") +
  labs(x="Date", y="Temperature") +
  scale_x_date(date_breaks = "1 month", date_minor_breaks = "1 week", date_labels = "%B")
```
### Zoom in

```{r}
# Temperature
ggplot(data, aes(x=date, y=temp)) +
  geom_line() +
  geom_smooth(col="red") +
  geom_hline(aes(yintercept = 62), color="red", linetype="dashed") +
  geom_hline(aes(yintercept = 70), color="red", linetype="dashed") +
  labs(x="Date", y="Temperature") +
  scale_x_date(date_breaks = "1 month", date_minor_breaks = "1 week", date_labels = "%B",
               limits = as.Date(c("2023-11-01", "2023-12-31")))
```



2) Relative humidity
```{r}
ggplot(data, aes(x=time, y=rh)) +
  geom_line()
```

Filtering plots 

Filter out by date range
```{r}
data %>% 
  filter(date > "2023-10-06") %>% 
  ggplot(aes(x=time, y=rh)) +
  geom_line()
```